In [3]:
import numpy as np

In [4]:
def oneHotEncode(column, uniqueValues):
    oneHotEncodedColumn = np.zeros((len(column), len(uniqueValues)))
    for i in range(len(column)):
        oneHotEncodedColumn[i][list(uniqueValues).index(column[i])] = 1
    return oneHotEncodedColumn.astype(int)

In [5]:
#Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice

#==> we keep the following columns: + means we one hot encode it, = means we keep it as is
#MSSubClass +, MSZoning =, LotFrontage =, Stree +, Alley +, LotShape +,
#LandContour +, Utilities +, LotConfig +, LandSlope +, Neighborhood +,
#Condition1 +, Condition2 +, BldgType +, HouseStyle +, OverallQual =,
#OverallCond =, // YearBuilt // =, // YearRemodAdd // =, RoofStyle +, RoofMatl +, 
#Exterior1st +, Exterior2nd +, MasVnrType +, MasVnrArea =, ExterQual +,
#ExterCond +, Foundation +, BsmtQual +, BsmtCond +, BsmtExposure +,
#BsmtFinType1 +, BsmtFinSF1 =, BsmtFinType2 +, BsmtFinSF2 =, BsmtUnfSF =,
#TotalBsmtSF =, Heating +, HeatingQC +, CentralAir +, Electrical +,
#1stFlrSF =, 2ndFlrSF =, LowQualFinSF =, GrLivArea =, BsmtFullBath =,
#BsmtHalfBath =, FullBath =, HalfBath =, Bedroom =, Kitchen =, // KitchenQual //,
#TotRmsAbvGrd =, // Functional // +, Fireplaces =, // FireplaceQu // +, 
#GarageType +, // GarageYrBlt // =, // GarageFinish + //, GarageCars =, 
#GarageArea =, // GarageQual // +, // GarageCond // +, // PavedDrive // +,
#WoodDeckSF =, OpenPorchSF =, EnclosedPorch =, 3SsnPorch =, ScreenPorch =,
#PoolArea =, // PoolQC // +, // Fence // +, ?? MiscFeature ?? +, ?? MiscVal ?? =,
#// MoSold //=, // YrSold // =, SaleType +, SaleCondition +

In [6]:
with open("train.csv") as f:
    lines = f.readlines()

header = lines[0]
lines = lines[1:]

data = np.array([line.split(",") for line in lines])

#increase print size
np.set_printoptions(threshold=np.inf)

print(header)
print(data.shape)



Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice

(1460, 81)


In [7]:
#MSSubClass
MSSubClass = data[:,1].astype(int)
uniqueMSSubClass = np.unique(MSSubClass)
#add missing values
uniqueMSSubClass = np.append(uniqueMSSubClass, 150)
uniqueMSSubClass.sort()
print(uniqueMSSubClass)

oneHotEncodedMSSubClass = oneHotEncode(MSSubClass, uniqueMSSubClass)

[ 20  30  40  45  50  60  70  75  80  85  90 120 150 160 180 190]


In [8]:
#MSZoning
MSZoning = data[:,2]
uniqueMSZoning = np.array(["A", "C (all)", "FV", "I", "RH", "RL", "RP", "RM"])
oneHotEncodedMSZoning = oneHotEncode(MSZoning, uniqueMSZoning)

print(uniqueMSZoning)

['A' 'C (all)' 'FV' 'I' 'RH' 'RL' 'RP' 'RM']


In [9]:
#LotFrontage
LotFrontage = data[:,3]
LotFrontage[LotFrontage == "NA"] = np.nan
LotFrontage = LotFrontage.astype(float)
print(LotFrontage[:20])

[65. 80. 68. 60. 84. 85. 75. nan 51. 50. 70. 85. nan 91. nan 51. nan 72.
 66. 70.]


In [10]:
#LotArea
LotArea = data[:,4].astype(float)

In [11]:
#Street
Street = data[:,5]
uniqueStreet = np.array(["Grvl", "Pave"])
oneHotEncodedStreet = oneHotEncode(Street, uniqueStreet)
print(oneHotEncodedStreet[:10]) #1 0 is rare

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


In [12]:
#Alley
Alley = data[:,6]
uniqueAlley = np.array(["Grvl", "Pave", "NA"])
oneHotEncodedAlley = oneHotEncode(Alley, uniqueAlley)
print(oneHotEncodedAlley[:10]) #almost all NA

[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [13]:
#LotShape
LotShape = data[:,7]
lotshape_mapping = {"Reg": 0, "IR1": 1, "IR2": 2, "IR3": 3}
LotShape = np.array([lotshape_mapping[shape] for shape in LotShape])
print(data[:20, 7])
print(LotShape[:20])

['Reg' 'Reg' 'IR1' 'IR1' 'IR1' 'IR1' 'Reg' 'IR1' 'Reg' 'Reg' 'Reg' 'IR1'
 'IR2' 'IR1' 'IR1' 'Reg' 'IR1' 'Reg' 'Reg' 'Reg']
[0 0 1 1 1 1 0 1 0 0 0 1 2 1 1 0 1 0 0 0]


In [14]:
#LandContour
LandContour = data[:,8]
landcontour_mapping = {"Lvl": 0, "Bnk": 1, "HLS": 2, "Low": 3}
LandContour = np.array([landcontour_mapping[contour] for contour in LandContour])
print(data[:10, 8])
print(LandContour[:10])

['Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl']
[0 0 0 0 0 0 0 0 0 0]


In [16]:
#Utilities
Utilities = data[:,9]
utilities_mapping = {"AllPub": 0, "NoSewr": 1, "NoSeWa": 2, "ELO": 3}
Utilities = np.array([utilities_mapping[utility] for utility in Utilities])
print(data[:10, 9])
print(Utilities[:10])

['AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub'
 'AllPub' 'AllPub']
[0 0 0 0 0 0 0 0 0 0]


In [17]:
#LotConfig
LotConfig = data[:,10]
uniqueLotConfig = np.array(["Inside", "Corner", "CulDSac", "FR2", "FR3"])
oneHotEncodedLotConfig = oneHotEncode(LotConfig, uniqueLotConfig)
print(oneHotEncodedLotConfig[:10])


[[1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


In [19]:
#LandSlope
LandSlope = data[:,11]
landslope_mapping = {"Gtl": 0, "Mod": 1, "Sev": 2}
LandSlope = np.array([landslope_mapping[slope] for slope in LandSlope])
print(data[:100, 11])
print(LandSlope[:100])

['Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Mod' 'Gtl' 'Mod' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [28]:
#Neighborhood
Neighborhood = data[:,12]
uniqueNeighborhood = np.array(["Blmngtn", "Blueste", "BrDale", "BrkSide", "ClearCr", 
                               "CollgCr", "Crawfor", "Edwards", "Gilbert", "IDOTRR", 
                               "MeadowV", "Mitchel", "NAmes", "NoRidge", "NPkVill", 
                               "NridgHt", "NWAmes", "OldTown", "SWISU", "Sawyer", 
                               "SawyerW", "Somerst", "StoneBr", "Timber", "Veenker"])
oneHotEncodedNeighborhood = oneHotEncode(Neighborhood, uniqueNeighborhood)
print(oneHotEncodedNeighborhood[:10])


[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [38]:
#Condition1
Condition1 = data[:,13]
uniqueCondition1 = np.array(["Artery", "Feedr", "Norm", "RRNn",
                             "RRAn", "PosN", "PosA", "RRNe", "RRAe"])
oneHotEncodedCondition1 = oneHotEncode(Condition1, uniqueCondition1)
# print(oneHotEncodedCondition1[:10])

#Condition2
Condition2 = data[:,14]
uniqueCondition2 = np.array(["Artery", "Feedr", "Norm", "RRNn",
                             "RRAn", "PosN", "PosA", "RRNe", "RRAe"])
oneHotEncodedCondition2 = oneHotEncode(Condition2, uniqueCondition2)

#union of condition1 and condition2
oneHotEncodedCondition = np.logical_or(oneHotEncodedCondition1, oneHotEncodedCondition2).astype(int)

print('\n', oneHotEncodedCondition[:10]) #can have multiple active conditions



 [[0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]]


In [41]:
#BldgType
BldgType = data[:,15]
uniqueBldgType = np.array(["1Fam", "2fmCon", "Duplex", "TwnhsE", "Twnhs"])
oneHotEncodedBldgType = oneHotEncode(BldgType, uniqueBldgType)
print(oneHotEncodedBldgType[:10])


[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


In [42]:
#HouseStyle
HouseStyle = data[:,16]
uniqueHouseStyle = np.array(["1Story", "1.5Fin", "1.5Unf", "2Story", "2.5Fin", "2.5Unf", "SFoyer", "SLvl"])
oneHotEncodedHouseStyle = oneHotEncode(HouseStyle, uniqueHouseStyle)
print(oneHotEncodedHouseStyle[:10])

[[0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


In [44]:
#OverallQual
OverallQual = data[:,17].astype(int)
print(OverallQual[:10])

#OverallCond
OverallCond = data[:,18].astype(int)
print(OverallCond[:10])


[7 6 7 7 8 5 8 7 7 5]
[5 8 5 5 5 5 5 6 5 6]


In [46]:
#YearBuilt
YearBuilt = data[:,19].astype(int)
print(YearBuilt[:10])

[2003 1976 2001 1915 2000 1993 2004 1973 1931 1939]
