In [2]:
import numpy as np

In [3]:
def oneHotEncode(column, uniqueValues):
    oneHotEncodedColumn = np.zeros((len(column), len(uniqueValues)))
    for i in range(len(column)):
        oneHotEncodedColumn[i][list(uniqueValues).index(column[i])] = 1
    return oneHotEncodedColumn.astype(int)

In [4]:
#Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice

#==> we keep the following columns: + means we one hot encode it, = means we keep it as is
#MSSubClass +, MSZoning =, LotFrontage =, Stree +, Alley +, LotShape +,
#LandContour +, Utilities +, LotConfig +, LandSlope +, Neighborhood +,
#Condition1 +, Condition2 +, BldgType +, HouseStyle +, OverallQual =,
#OverallCond =, // YearBuilt // =, // YearRemodAdd // =, RoofStyle +, RoofMatl +, 
#Exterior1st +, Exterior2nd +, MasVnrType +, MasVnrArea =, ExterQual +,
#ExterCond +, Foundation +, BsmtQual +, BsmtCond +, BsmtExposure +,
#BsmtFinType1 +, BsmtFinSF1 =, BsmtFinType2 +, BsmtFinSF2 =, BsmtUnfSF =,
#TotalBsmtSF =, Heating +, HeatingQC +, CentralAir +, Electrical +,
#1stFlrSF =, 2ndFlrSF =, LowQualFinSF =, GrLivArea =, BsmtFullBath =,
#BsmtHalfBath =, FullBath =, HalfBath =, Bedroom =, Kitchen =, // KitchenQual //,
#TotRmsAbvGrd =, // Functional // +, Fireplaces =, // FireplaceQu // +, 
#GarageType +, // GarageYrBlt // =, // GarageFinish + //, GarageCars =, 
#GarageArea =, // GarageQual // +, // GarageCond // +, // PavedDrive // +,
#WoodDeckSF =, OpenPorchSF =, EnclosedPorch =, 3SsnPorch =, ScreenPorch =,
#PoolArea =, // PoolQC // +, // Fence // +, ?? MiscFeature ?? +, ?? MiscVal ?? =,
#// MoSold //=, // YrSold // =, SaleType +, SaleCondition +

In [34]:
with open("train.csv") as f:
    lines = f.readlines()

header = lines[0].split(",") #header
lines = lines[1:]

data = np.array([line.split(",") for line in lines])

#increase print size
np.set_printoptions(threshold=np.inf)

print(header)
print(data.shape)



['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC'

In [6]:
#MSSubClass
MSSubClass = data[:,1].astype(int)
uniqueMSSubClass = np.unique(MSSubClass)
#add missing values
uniqueMSSubClass = np.append(uniqueMSSubClass, 150)
uniqueMSSubClass.sort()
print(uniqueMSSubClass)

oneHotEncodedMSSubClass = oneHotEncode(MSSubClass, uniqueMSSubClass)

[ 20  30  40  45  50  60  70  75  80  85  90 120 150 160 180 190]


In [7]:
#MSZoning
MSZoning = data[:,2]
uniqueMSZoning = np.array(["A", "C (all)", "FV", "I", "RH", "RL", "RP", "RM"])
oneHotEncodedMSZoning = oneHotEncode(MSZoning, uniqueMSZoning)

print(uniqueMSZoning)

['A' 'C (all)' 'FV' 'I' 'RH' 'RL' 'RP' 'RM']


In [8]:
#LotFrontage
LotFrontage = data[:,3]
LotFrontage[LotFrontage == "NA"] = np.nan
LotFrontage = LotFrontage.astype(float)
print(LotFrontage[:20])

[65. 80. 68. 60. 84. 85. 75. nan 51. 50. 70. 85. nan 91. nan 51. nan 72.
 66. 70.]


In [9]:
#LotArea
LotArea = data[:,4].astype(float)

In [10]:
#Street
Street = data[:,5]
uniqueStreet = np.array(["Grvl", "Pave"])
oneHotEncodedStreet = oneHotEncode(Street, uniqueStreet)
print(oneHotEncodedStreet[:10]) #1 0 is rare

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


In [11]:
#Alley
Alley = data[:,6]
uniqueAlley = np.array(["Grvl", "Pave", "NA"])
oneHotEncodedAlley = oneHotEncode(Alley, uniqueAlley)
print(oneHotEncodedAlley[:10]) #almost all NA

[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [12]:
#LotShape
LotShape = data[:,7]
lotshape_mapping = {"Reg": 0, "IR1": 1, "IR2": 2, "IR3": 3}
LotShape = np.array([lotshape_mapping[shape] for shape in LotShape])
print(data[:20, 7])
print(LotShape[:20])

['Reg' 'Reg' 'IR1' 'IR1' 'IR1' 'IR1' 'Reg' 'IR1' 'Reg' 'Reg' 'Reg' 'IR1'
 'IR2' 'IR1' 'IR1' 'Reg' 'IR1' 'Reg' 'Reg' 'Reg']
[0 0 1 1 1 1 0 1 0 0 0 1 2 1 1 0 1 0 0 0]


In [13]:
#LandContour
LandContour = data[:,8]
landcontour_mapping = {"Lvl": 0, "Bnk": 1, "HLS": 2, "Low": 3}
LandContour = np.array([landcontour_mapping[contour] for contour in LandContour])
print(data[:10, 8])
print(LandContour[:10])

['Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl' 'Lvl']
[0 0 0 0 0 0 0 0 0 0]


In [14]:
#Utilities
Utilities = data[:,9]
utilities_mapping = {"AllPub": 0, "NoSewr": 1, "NoSeWa": 2, "ELO": 3}
Utilities = np.array([utilities_mapping[utility] for utility in Utilities])
print(data[:10, 9])
print(Utilities[:10])

['AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub' 'AllPub'
 'AllPub' 'AllPub']
[0 0 0 0 0 0 0 0 0 0]


In [15]:
#LotConfig
LotConfig = data[:,10]
uniqueLotConfig = np.array(["Inside", "Corner", "CulDSac", "FR2", "FR3"])
oneHotEncodedLotConfig = oneHotEncode(LotConfig, uniqueLotConfig)
print(oneHotEncodedLotConfig[:10])


[[1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


In [16]:
#LandSlope
LandSlope = data[:,11]
landslope_mapping = {"Gtl": 0, "Mod": 1, "Sev": 2}
LandSlope = np.array([landslope_mapping[slope] for slope in LandSlope])
print(data[:100, 11])
print(LandSlope[:100])

['Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Mod' 'Gtl' 'Mod' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl' 'Gtl'
 'Gtl' 'Gtl' 'Gtl' 'Gtl']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
#Neighborhood
Neighborhood = data[:,12]
uniqueNeighborhood = np.array(["Blmngtn", "Blueste", "BrDale", "BrkSide", "ClearCr", 
                               "CollgCr", "Crawfor", "Edwards", "Gilbert", "IDOTRR", 
                               "MeadowV", "Mitchel", "NAmes", "NoRidge", "NPkVill", 
                               "NridgHt", "NWAmes", "OldTown", "SWISU", "Sawyer", 
                               "SawyerW", "Somerst", "StoneBr", "Timber", "Veenker"])
oneHotEncodedNeighborhood = oneHotEncode(Neighborhood, uniqueNeighborhood)
print(oneHotEncodedNeighborhood[:10])


[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [18]:
#Condition1
Condition1 = data[:,13]
uniqueCondition1 = np.array(["Artery", "Feedr", "Norm", "RRNn",
                             "RRAn", "PosN", "PosA", "RRNe", "RRAe"])
oneHotEncodedCondition1 = oneHotEncode(Condition1, uniqueCondition1)
# print(oneHotEncodedCondition1[:10])

#Condition2
Condition2 = data[:,14]
uniqueCondition2 = np.array(["Artery", "Feedr", "Norm", "RRNn",
                             "RRAn", "PosN", "PosA", "RRNe", "RRAe"])
oneHotEncodedCondition2 = oneHotEncode(Condition2, uniqueCondition2)

#union of condition1 and condition2
oneHotEncodedCondition = np.logical_or(oneHotEncodedCondition1, oneHotEncodedCondition2).astype(int)

print('\n', oneHotEncodedCondition[:10]) #can have multiple active conditions



 [[0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]]


In [19]:
#BldgType
BldgType = data[:,15]
uniqueBldgType = np.array(["1Fam", "2fmCon", "Duplex", "TwnhsE", "Twnhs"])
oneHotEncodedBldgType = oneHotEncode(BldgType, uniqueBldgType)
print(oneHotEncodedBldgType[:10])


[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]


In [20]:
#HouseStyle
HouseStyle = data[:,16]
uniqueHouseStyle = np.array(["1Story", "1.5Fin", "1.5Unf", "2Story", "2.5Fin", "2.5Unf", "SFoyer", "SLvl"])
oneHotEncodedHouseStyle = oneHotEncode(HouseStyle, uniqueHouseStyle)
print(oneHotEncodedHouseStyle[:10])

[[0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


In [21]:
#OverallQual
OverallQual = data[:,17].astype(int)
print(OverallQual[:10])

#OverallCond
OverallCond = data[:,18].astype(int)
print(OverallCond[:10])


[7 6 7 7 8 5 8 7 7 5]
[5 8 5 5 5 5 5 6 5 6]


In [40]:
#Get sold year
YearSold = data[:,77].astype(int)
print(YearSold[:10])

[2008 2007 2008 2006 2008 2009 2007 2009 2008 2008]


In [42]:
#YearBuilt
YearBuilt = data[:,19].astype(int)
print(YearBuilt[:10])

delta_YearSold_YearBuilt = YearSold - YearBuilt
print(delta_YearSold_YearBuilt[:10])

[2003 1976 2001 1915 2000 1993 2004 1973 1931 1939]
[ 5 31  7 91  8 16  3 36 77 69]


In [43]:
#YearRemodAdd
YearRemodAdd = data[:,20].astype(int)

delta_YearSold_YearRemodAdd = YearSold - YearRemodAdd
print(delta_YearSold_YearRemodAdd[:10])

[ 5 31  6 36  8 14  2 36 58 58]


In [48]:
#RoofStyle
RoofStyle = data[:,21]
uniqueRoofStyle = np.array(["Flat", "Gable", "Gambrel", "Hip", "Mansard", "Shed"])
oneHotEncodedRoofStyle = oneHotEncode(RoofStyle, uniqueRoofStyle)
print(oneHotEncodedRoofStyle[:10])

[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]


In [49]:
#RoofMatl
RoofMatl = data[:,22]
uniqueRoofMatl = np.array(["ClyTile", "CompShg", "Membran", "Metal", "Roll", "Tar&Grv", "WdShake", "WdShngl"])
oneHotEncodedRoofMatl = oneHotEncode(RoofMatl, uniqueRoofMatl)
print(oneHotEncodedRoofMatl[:10])

[[0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]


In [66]:
#Exterior1st
Exterior1st = data[:,23]
Exterior1st[Exterior1st == "Wd Shng"] = "WdShing"
Exterior1st[Exterior1st == "Brk Cmn"] = "BrkComm"
Exterior1st[Exterior1st == "CmentBd"] = "CemntBd"

uniqueExterior = np.array(["AsbShng", "AsphShn", "BrkComm", "BrkFace", "CBlock", 
                              "CemntBd", "HdBoard", "ImStucc", "MetalSd", "Other", 
                              "Plywood", "PreCast", "Stone", "Stucco", "VinylSd", 
                              "Wd Sdng", "WdShing"])
oneHotEncodedExterior1st = oneHotEncode(Exterior1st, uniqueExterior)

#Exterior2nd
Exterior2nd = data[:,24]
Exterior2nd[Exterior2nd == "Wd Shng"] = "WdShing"
Exterior2nd[Exterior2nd == "Brk Cmn"] = "BrkComm"
Exterior2nd[Exterior2nd == "CmentBd"] = "CemntBd"
oneHotEncodedExterior2nd = oneHotEncode(Exterior2nd, uniqueExterior)

#union of exterior1st and exterior2nd
oneHotEncodedExterior = np.logical_or(oneHotEncodedExterior1st, oneHotEncodedExterior2nd).astype(int)
print(oneHotEncodedExterior[:10])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]


In [67]:
#MasVnrType
MasVnrType = data[:,25]
MasVnrType[MasVnrType == "None"] = "NA"
uniqueMasVnrType = np.array(["BrkCmn", "BrkFace", "CBlock", "NA", "Stone"])
oneHotEncodedMasVnrType = oneHotEncode(MasVnrType, uniqueMasVnrType)
print(oneHotEncodedMasVnrType[:10])

[[0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]]


In [79]:
#MasVnrArea
MasVnrArea = data[:,26]
MasVnrArea[MasVnrArea == "NA"] = np.nan
MasVnrArea = MasVnrArea.astype(float)
print(MasVnrArea[:100])

[ 196.    0.  162.    0.  350.    0.  186.  240.    0.    0.    0.  286.
    0.  306.  212.    0.  180.    0.    0.    0.  380.    0.  281.    0.
    0.  640.    0.  200.    0.    0.    0.    0.    0.    0.  246.  132.
    0.  650.    0.    0.  101.    0.    0.    0.    0.  412.    0.    0.
    0.    0.    0.    0.    0.    0.    0.  272.  456.    0. 1031.    0.
    0.    0.  178.    0.  573.  344.  287.  167.    0.    0. 1115.    0.
   40.  104.    0.    0.    0.    0.    0.    0.  576.  443.  468.   66.
   22.  284.    0.   76.    0.    0.    0.  203.    0.    0.    0.   68.
  183.   48.    0.    0.]


In [73]:
#ExterQual
ExterQual = data[:,27]
exterqual_mapping = {"Ex": 0, "Gd": 1, "TA": 2, "Fa": 3, "Po": 4}
ExterQual = np.array([exterqual_mapping[qual] for qual in ExterQual])
print(data[:10, 27])
print(ExterQual[:10])

['Gd' 'TA' 'Gd' 'TA' 'Gd' 'TA' 'Gd' 'TA' 'TA' 'TA']
[1 2 1 2 1 2 1 2 2 2]


In [74]:
#ExterCond
ExterCond = data[:,28]
extercond_mapping = {"Ex": 0, "Gd": 1, "TA": 2, "Fa": 3, "Po": 4}
ExterCond = np.array([extercond_mapping[cond] for cond in ExterCond])
print(data[:10, 28])
print(ExterCond[:10])

['TA' 'TA' 'TA' 'TA' 'TA' 'TA' 'TA' 'TA' 'TA' 'TA']
[2 2 2 2 2 2 2 2 2 2]


In [75]:
#Foundation
Foundation = data[:,29]
uniqueFoundation = np.array(["BrkTil", "CBlock", "PConc", "Slab", "Stone", "Wood"])
oneHotEncodedFoundation = oneHotEncode(Foundation, uniqueFoundation)
print(oneHotEncodedFoundation[:10])


[[0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]


In [80]:
#BsmtQual
BsmtQual = data[:,30]
BsmtQual_mapping = {"Ex": 0, "Gd": 1, "TA": 2, "Fa": 3, "Po": 4, "NA": 5}
BsmtQual = np.array([BsmtQual_mapping[qual] for qual in BsmtQual])
print(data[:10, 30])
print(BsmtQual[:10])

['Gd' 'Gd' 'Gd' 'TA' 'Gd' 'Gd' 'Ex' 'Gd' 'TA' 'TA']
[1 1 1 2 1 1 0 1 2 2]


In [81]:
#BsmtCond
BsmtCond = data[:,31]
BsmtCond_mapping = {"Ex": 0, "Gd": 1, "TA": 2, "Fa": 3, "Po": 4, "NA": 5}
BsmtCond = np.array([BsmtCond_mapping[cond] for cond in BsmtCond])
print(data[:10, 31])
print(BsmtCond[:10])

['TA' 'TA' 'TA' 'Gd' 'TA' 'TA' 'TA' 'TA' 'TA' 'TA']
[2 2 2 1 2 2 2 2 2 2]


In [82]:
#BsmtExposure
BsmtExposure = data[:,32]
BsmtExposure_mapping = {"Gd": 0, "Av": 1, "Mn": 2, "No": 3, "NA": 4}
BsmtExposure = np.array([BsmtExposure_mapping[exposure] for exposure in BsmtExposure])
print(data[:10, 32])
print(BsmtExposure[:10])

['No' 'Gd' 'Mn' 'No' 'Av' 'No' 'Av' 'Mn' 'No' 'No']
[3 0 2 3 1 3 1 2 3 3]


In [83]:
#BsmtFinType1
BsmtFinType1 = data[:,33]
BsmtFinType1_mapping = {"GLQ": 0, "ALQ": 1, "BLQ": 2, "Rec": 3, "LwQ": 4, "Unf": 5, "NA": 6}
BsmtFinType1 = np.array([BsmtFinType1_mapping[finType] for finType in BsmtFinType1])
print(data[:10, 33])
print(BsmtFinType1[:10])

['GLQ' 'ALQ' 'GLQ' 'ALQ' 'GLQ' 'GLQ' 'GLQ' 'ALQ' 'Unf' 'GLQ']
[0 1 0 1 0 0 0 1 5 0]


In [84]:
#BsmtFinSF1
BsmtFinSF1 = data[:,34].astype(float)
print(BsmtFinSF1[:10])

[ 706.  978.  486.  216.  655.  732. 1369.  859.    0.  851.]
